// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about_index from "./routes/about/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $resume_index from "./routes/resume/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $ThemeProvider from "./islands/ThemeProvider.tsx";
import * as $TypingAnimation from "./islands/TypingAnimation.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about/index.tsx": $about_index,
    "./routes/index.tsx": $index,
    "./routes/resume/index.tsx": $resume_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/ThemeProvider.tsx": $ThemeProvider,
    "./islands/TypingAnimation.tsx": $TypingAnimation,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
